export const GAME = {
  BASE_WIDTH: 480,
  BASE_HEIGHT: 800,
  FPS_CAP: 60,
  FIXED_DT: 1 / 60,
  MAX_CATCHUP_STEPS: 5,
};

export const WORLD = {
  GRAVITY: 1700,
  JUMP_IMPULSE: 525,
  MAX_FALL_SPEED: 1100,
  ROT_UP: -0.55,
  ROT_DOWN: 1.35,
};

export const OWL = {
  X: 140,
  RADIUS: 18,
  HIT_RADIUS_SCALE: 0.8,
  WIDTH: 42,
  HEIGHT: 34,
  RENDER_W: 64,
  RENDER_Y_OFFSET: -2,
};

export const OBSTACLE = {
  WIDTH: 78,
  MIN_GAP: 176,
  MAX_GAP: 262,
  MIN_TOP: 110,
  MIN_BOTTOM: 140,
  BASE_SPEED: 245,
  SPEED_MAX: 450,

  CLOUD_HITBOX_HEIGHT: 84,
  CLOUD_HITBOX_INSET_X: 8,

  TORNADO_HITBOX_HEIGHT: 150,
  TORNADO_HITBOX_INSET_X: 10,

  CLOUD_VISUAL_MIN_HEIGHT: 92,
  TORNADO_VISUAL_MIN_HEIGHT: 170,
  GROUND_VISUAL_INSET: 18,

  CLOUD_SWELL_SCALE_MIN: 1.12,
  CLOUD_SWELL_SCALE_MAX: 1.22,

  TORNADO_SURGE_SCALE_MIN: 1.18,
  TORNADO_SURGE_SCALE_MAX: 1.34,
  TORNADO_SURGE_HITBOX_BONUS_MIN: 16,
  TORNADO_SURGE_HITBOX_BONUS_MAX: 28,
};

export const SPAWN = {
  BASE_INTERVAL: 1.32,
  MIN_INTERVAL: 1.02,

  EASY_INJECTION_EVERY: 10,
  EASY_INJECTION_COUNT: 3,
  EASY_GAP_BONUS: 60,
  EASY_SPEED_PENALTY: 30,

  OPENING_OBSTACLES: 4,
  OPENING_GAP_BONUS: 35,
  OPENING_SPEED_PENALTY: 35,
  OPENING_CENTER_SHIFT_PX: 55,
  CENTER_EDGE_MARGIN_PX: 28,

  MAX_CENTER_SHIFT_PX: 90,
  SPAWN_X: 520,

  CLOUD_SWELL_EVERY: 4,
  TORNADO_SURGE_EVERY: 6,
};

export const DIFFICULTY = {
  SPEED_RAMP_PER_SEC: 5.5,
  GAP_SHRINK_PER_SEC: 0.55,
  INTERVAL_SHRINK_PER_SEC: 0.006,
};

export const FRACTURE = {
  TRIGGER_EVERY_PASSES: 6,
  TRANSITION_DURATION: 0.72,
  GLIDE_DURATION: 4.4,
  REENTRY_DURATION: 1.1,
  REENTRY_INVULN: 0.5,
  GLIDE_GRAVITY_SCALE: 0.38,
  GLIDE_JUMP_SCALE: 0.56,
  GLIDE_MAX_FALL_SCALE: 0.55,
  GLIDE_ROT_DOWN_SCALE: 0.45,
  VISUAL_SPLIT_Y: 0.48,
  VISUAL_SHEAR_PX: 18,
  REWARD_SPEED: 250,
  REWARD_RADIUS: 14,
  REWARD_INTERVAL: 0.28,
  REWARD_POINTS: 1,
  REWARD_TRACK_TOP: 180,
  REWARD_TRACK_BOTTOM: 620,
};

export const AUDIO = {
  MASTER: 1.0,
  SFX: 0.9,
  MUSIC: 0.25,
  FLAP: 0.75,
  SCORE: 0.35,
  HIT: 0.95,
};

export const STORAGE_KEYS = {
  HIGH_SCORE: "owlfly_highscore_v1",
  SETTINGS: "owlfly_settings_v1",
  PROFILE: "owlfly_profile_v1",
};