$ErrorActionPreference = "Stop"

# tooling\build.ps1 -> project root is parent of tooling/
$root = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $root "src"
$out  = Join-Path $root "web\game.js"

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $out) | Out-Null
Write-Host "Building OwlFly -> $out"

function Transform-ToClassicScript([string]$code) {
  # Remove ESM imports (concat order provides symbols)
  $code = $code -replace '(?m)^\s*import\s+[^;]+;\s*$', ''

  # Remove default exports (rare)
  $code = $code -replace '(?m)^\s*export\s+default\s+', ''

  # Strip named exports: export function|const|class|let|var
  $code = $code -replace '(?m)^\s*export\s+(function|const|class|let|var)\s+', '$1 '

  # Remove export lists: export { a, b as c };
  $code = $code -replace '(?m)^\s*export\s*\{[^}]+\}\s*;\s*$', ''

  return $code.TrimEnd()
}

$banner = @"
/**
 * OwlFly — built bundle (generated)
 * Classic script bundle (no imports/exports)
 * Do not edit this file directly.
 */
"@
Set-Content -LiteralPath $out -Encoding UTF8 -Value $banner

$files = @(
  "core\constants.js",
  "core\audio.js",
  "core\rng.js",
  "core\storage.js",
  "engine\physics.js",
  "engine\collision.js",
  "engine\difficulty.js",
  "engine\input.js",
  "engine\gameLoop.js",
  "engine\entities\owl.js",
  "engine\entities\obstaclePair.js",
  "systems\scoring.js",
  "systems\spawner.js",
  "render\renderer.js",
  "ui\menu.js",
  "ui\hud.js",
  "ui\gameOver.js",
  "app\boot.js"
)

foreach ($f in $files) {
  $p = Join-Path $src $f
  if (!(Test-Path $p)) { throw "Missing source file: $p" }

  $raw = Get-Content -LiteralPath $p -Raw -Encoding UTF8
  $x = Transform-ToClassicScript $raw

  Add-Content -LiteralPath $out -Encoding UTF8 -Value "`n`n// ===== FILE: src/$($f -replace '\\','/') =====`n"
  Add-Content -LiteralPath $out -Encoding UTF8 -Value $x
}

# Auto-start
Add-Content -LiteralPath $out -Encoding UTF8 -Value "`n`n// ===== AUTO-BOOT =====`nboot();`n"

# Install prod index as default after build
Copy-Item -Force (Join-Path $root "web\index.prod.html") (Join-Path $root "web\index.html")
Write-Host "Prod index.html installed."

Write-Host "Build complete."
