import fs from "node:fs";
import path from "node:path";

const ROOT_DIR = process.cwd();
const SRC_DIR = path.join(ROOT_DIR, "src");
const WEB_DIR = path.join(ROOT_DIR, "web");
const OUT_FILE = path.join(WEB_DIR, "game.js");
const PROD_INDEX_SRC = path.join(WEB_DIR, "index.prod.html");
const PROD_INDEX_DEST = path.join(WEB_DIR, "index.html");

fs.mkdirSync(WEB_DIR, { recursive: true });

console.log(`Building OwlFly -> ${OUT_FILE}`);

const FILES = [
  "core/constants.js",
  "core/rng.js",
  "core/storage.js",
  "core/audio.js",
  "core/music.js",
  "core/progress.js",
  "core/themes.js",
  "engine/physics.js",
  "engine/collision.js",
  "engine/difficulty.js",
  "engine/input.js",
  "engine/gameLoop.js",
  "engine/entities/owl.js",
  "engine/entities/obstaclePair/math.js",
  "engine/entities/obstaclePair/geometry.js",
  "engine/entities/obstaclePair/motion.js",
  "engine/entities/obstaclePair/visualState.js",
  "engine/entities/obstaclePair.js",
  "systems/scoring.js",
  "systems/spawner.js",
  "render/renderer.js",
  "ui/menu.js",
  "ui/hud.js",
  "ui/gameOver.js",
  "app/boot.js",
];

let output = `/**
 * OwlFly — built bundle (generated)
 * Do not edit this file directly.
 */
`;

for (const f of FILES) {
  const fullPath = path.join(SRC_DIR, f);

  if (!fs.existsSync(fullPath)) {
    throw new Error(`Missing source file: ${fullPath}`);
  }

  let code = fs.readFileSync(fullPath, "utf8");

  code = code.replace(/^\s*import[\s\S]*?from\s+["'][^"']+["'];?\s*$/gm, "");
  code = code.replace(/^\s*import\s+["'][^"']+["'];?\s*$/gm, "");
  code = code.replace(/^\s*export\s+default\s+/gm, "");
  code = code.replace(/^\s*export\s+/gm, "");

  output += `\n\n// ===== FILE: src/${f} =====\n\n`;
  output += code;
}

fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`Built: ${OUT_FILE}`);

if (fs.existsSync(PROD_INDEX_SRC)) {
  fs.copyFileSync(PROD_INDEX_SRC, PROD_INDEX_DEST);
  console.log("Prod index.html installed.");
} else {
  console.warn(`No prod index found at: ${PROD_INDEX_SRC}`);
}